<a href="https://colab.research.google.com/github/huymarvel/100-days-of-code/blob/main/BT3_3_M%E1%BA%A3ng_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
arr = np.ones((3,3))
arr = arr.astype(bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
arr = np.ones((3,3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
print(arr_1D)
arr_2D = arr_1D.reshape(3,3)
print(arr_2D)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
arr_2D=arr_2D[:,[2,1,0]]
print(arr_2D)

[[2 1 0]
 [5 4 3]
 [8 7 6]]
