<a href="https://colab.research.google.com/github/huymarvel/100-days-of-code/blob/main/BT_3_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

In [24]:
arr = np.arange(10)
print(arr)
print(type(arr))
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [25]:
arr_odd = arr[arr%2!=0]
arr_even = arr[arr%2==0]
print("Odd array: \n", arr_odd)
print("Even array: \n", arr_even)

Odd array: 
 [1 3 5 7 9]
Even array: 
 [0 2 4 6 8]


In [26]:
arr_update_1 = np.where(arr%2==0,arr,100)
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]


In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
 arr_update_1 = arr.copy()
 arr_update_1[arr_update_1%2!=0] = 100
 print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]


In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])