<a href="https://colab.research.google.com/github/huymarvel/100-days-of-code/blob/main/Numpy_BT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [26]:
arr_1 = np.array([9.0, 7.5, 6.8, 8.9, 6.2])

In [27]:
print(arr_1)

[9.  7.5 6.8 8.9 6.2]


In [28]:
type(arr_1)

numpy.ndarray

In [29]:
arr_1.dtype

dtype('float64')

In [30]:
print("Mean: ", arr_1.mean())
print("Max: ", arr_1.max())

Mean:  7.6800000000000015
Max:  9.0


In [31]:
arr_1+0.5

array([9.5, 8. , 7.3, 9.4, 6.7])

In [32]:
arr_1.sort()
arr_1

array([6.2, 6.8, 7.5, 8.9, 9. ])

In [33]:
arr_1[::-1]

array([9. , 8.9, 7.5, 6.8, 6.2])

In [35]:
arr_2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
arr_2[0,2]

3